name: Update IPTV Playlist

on:
  schedule:
    - cron: '0 */12 * * *' # Yeh din mein 2 baar (har 12 ghante mein) automatically chalega
  workflow_dispatch: # Isse aap manually bhi GitHub button se run kar sakte ho

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install node-fetch@2

    - name: Run Script
      run: node update-playlist.js

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-update IPTV playlist.m3u"
        file_pattern: playlist.m3u
